OC.L10N.register(
    "sharepoint",
    {
    "SharePoint" : "SharePoint",
    "Host" : "Ostiz",
    "Document Library" : "Lervdi diell",
    "SharePoint Backend" : "Backend SharePoint",
    "SharePoint Backend for External storages" : "Backend SharePoint evit ar bern diavaez",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nRequires Nextcloud 10 or newer. Supports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Ar Vacknd SharePoint a aotre an administratour ouzhpenna lervdioù diell SharePoint evell teuliadom Nextcloud. Reiñ a ra un dremenn aes da roadennoù SharePoint e memes lec'h ag an hini m'emañ ar restroù all, aesaat ar c'henlabourat hag ar rannñ e barzh ha dre bevenn ar framm. A Posuple eo d'an implijourienn implij ar burev kliant, ar meziantoù pellgomzer-ezouk pe etrefas-web ha lakaat klavioù, rannañ, displegiñ, ha embann asemles war restroù SharePoint evel n'euz forzh peseurt roadennoù all war Nextcloud.\n\nEzhomp ez eus eus Nextcloud 10 pe nevesoc'h. Douget eo SharePoint 2013 ha SharePoint 2016. Tizet vez SharePoint gant Nextcloud dre ar SharePoint TREST API ha implijet a vez an dilesa NTLM. Nexcloud a zouj ouzh aotreoù tizañ restr kemprennet gant e stumm impijer hennadur. Stumm ha rannañ a vez graet gant Nextcloud.\n\nTitouroù all diwar ben SharePoint ha External Storage war [https://nextcloud.com/storage/](https://nextcloud.com/storage/)"
},
"nplurals=5; plural=((n%10 == 1) && (n%100 != 11) && (n%100 !=71) && (n%100 !=91) ? 0 :(n%10 == 2) && (n%100 != 12) && (n%100 !=72) && (n%100 !=92) ? 1 :(n%10 ==3 || n%10==4 || n%10==9) && (n%100 < 10 || n% 100 > 19) && (n%100 < 70 || n%100 > 79) && (n%100 < 90 || n%100 > 99) ? 2 :(n != 0 && n % 1000000 == 0) ? 3 : 4);");
