OC.L10N.register(
    "sharepoint",
    {
    "Enforce NTLM auth" : "Επιβολή πιστοποίησης NTLM",
    "Acquiring a SAML token is attempted first by default." : "Η απόκτηση ενός διακριτικού SAML επιχειρείται πρώτα από προεπιλογή.",
    "SharePoint" : "Κοινόχρηστο Σημείο",
    "Host" : "Υπολογιστής φιλοξενίας",
    "Document Library" : "Βιβλιοθήκη Εγγράφων",
    "SharePoint Backend" : "Σύστημα υποστήριξης SharePoint",
    "SharePoint Backend for External storages" : "Σύστημα υποστήριξης SharePoint για εξωτερικά μέσα αποθήκευσης",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nRequires Nextcloud 10 or newer. Supports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Το Σύστημα υποστήριξης SharePoint επιτρέπει στους διαχειριστές να εισάγουν στο βιβλιοθήκες εγγράφων του SharePoint σαν φακέλους στο Nextcloud. Ένας εύκολος τρόπος πρόσβασης για τους χρήστες στα δεδομένα Sharepoint στο ίδιο μέρος με τα υπόλοιπα αρχεία τους, διευκολύνοντας τη συνεργασία μεταξύ διάφορων οργανισμών. Οι χρήστες μπορούν χρησιμοποιήσουν τον τον πελάτη για επιτραπέζιους υπολογιστές, εφαρμογές για κινητά ή διεπαφή ιστού και να σχολιάσουν, να επισημάνουν ή να επεξεργαστούν αρχεία του Sharepoint όπως τα υπόλοιπα αρχεία του Nextcloud.\n\nΑπαιτείται Nextcloud 10 ή νεότερο. Υποστηρίζονται του Sharepoint 2013 και 2016. Το Nextcloud είναι προσβάσιμο μέσω του Sharepoint REST API με χρήση πιστοποίησης NTLM. Το Nextcloud σέβεται τα δικαιώματα πρόσβασης αρχείων που σχετίζονται με τα διαμορφωμένα διαπιστευτήρια χρήστη. Η διαχείριση εκδόσεων και η κοινή χρήση γίνεται από το Nextcloud.\n\nΜάθετε περισσότερα για την Εξωτερική αποθήκευση και το Sharepoint στη διέθυνση[https://nextcloud.com/storage/](https://nextcloud.com/storage/)",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nSupports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Το Σύστημα υποστήριξης Sharepoint επιτρέπει στους διαχειριστές να προσθέτουν βιβλιοθήκες εγγράφων του Sharepoint ως φακέλους στο Nextcloud. Αυτό προσφέρει έναν εύκολο τρόπο για τους χρήστες να έχουν πρόσβαση στα δεδομένα του Sharepoint στο ίδιο μέρος όπου βρίσκουν τα άλλα αρχεία τους, διευκολύνοντας τη συνεργασία και την κοινή χρήση εντός και εκτός των συνόρων του οργανισμού. Οι χρήστες μπορούν να χρησιμοποιήσουν τον πελάτη για επιτραπέζιους υπολογιστές, εφαρμογές για κινητά ή διεπαφή ιστού και να σχολιάσουν, να επισημάνουν, να μοιραστούν και να επεξεργαστούν από κοινού αρχεία στο Sharepoint, όπως και με οποιαδήποτε άλλα δεδομένα στο Nextcloud.\n\nΥποστηρίζει Sharepoint 2013 και 2016. Το Nextcloud αποκτά πρόσβαση στο Sharepoint μέσω του Sharepoint REST API και χρησιμοποιεί πιστοποίηση NTLM. Το Nextcloud σέβεται τα δικαιώματα πρόσβασης αρχείων που σχετίζονται με τα διαμορφωμένα διαπιστευτήρια χρήστη. Η διαχείριση εκδόσεων και η κοινή χρήση γίνεται από το Nextcloud.\n\nΜάθετε περισσότερα σχετικά με την Εξωτερική αποθήκευση και το Sharepoint στη διεύθυνση [https://nextcloud.com/storage/](https://nextcloud.com/storage/)"
},
"nplurals=2; plural=(n != 1);");
