OC.L10N.register(
    "sharepoint",
    {
    "SharePoint" : "SharePoint",
    "Host" : "Hôte",
    "Document Library" : "Bibliothèque de documents",
    "SharePoint Backend" : "Arrière-plan SharePoint",
    "SharePoint Backend for External storages" : "SharePoint comme stockage externe",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nRequires Nextcloud 10 or newer. Supports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Le Sharepoint Backend permet aux administrateurs d'ajouter des bibliothèques de documents Sharepoint en tant que dossiers dans Nextcloud. Cela permet aux utilisateurs d'accéder facilement aux données Sharepoint au même endroit où ils trouvent leurs autres fichiers, ce qui facilite la collaboration et le partage au sein et à travers les frontières de l'organisation. Les utilisateurs peuvent utiliser le client de bureau, les applications mobiles ou l'interface Web et commenter, étiqueter, partager et éditer des fichiers en collaboration sur Sharepoint, comme avec n'importe quelle autre donnée sur Nextcloud.\n\nNécessite Nextcloud 10 ou plus récent. Prend en charge Sharepoint 2013 et 2016. Nextcloud accède à Sharepoint via l'API REST Sharepoint et utilise l'authentification NTLM. Nextcloud respecte les autorisations d'accès aux fichiers associées à ses informations d'identification utilisateur configurées. La gestion des versions et le partage sont gérés par Nextcloud.\n\nEn savoir plus sur Stockage externe et Sharepoint sur [https://nextcloud.com/storage/](https://nextcloud.com/storage/)"
},
"nplurals=2; plural=(n > 1);");
