OC.L10N.register(
    "sharepoint",
    {
    "Enforce NTLM auth" : "Az NTLM hitelesítés kikényszerítése",
    "Acquiring a SAML token is attempted first by default." : "Alapértelmezés szerint először SAML tokent próbál szerezni.",
    "SharePoint" : "SharePoint",
    "Host" : "Kiszolgáló",
    "Document Library" : "Dokumentumtár",
    "SharePoint Backend" : "SharePoint háttérszolgáltatás",
    "SharePoint Backend for External storages" : "SharePoint háttérszolgáltatás a külső tárolókhoz",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nSupports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "A Sharepoint Backend lehetővé teszi a rendszergazdák számára, hogy a Sharepoint dokumentumkönyvtárakat mappaként adják hozzá a Nextcloudhoz. Ez egyszerű módot kínál a felhasználók számára a Sharepoint adatokhoz való hozzáférésre ugyanazon a helyen, ahol más fájljaikat megtalálják, megkönnyítve az együttműködést és a megosztást a szervezet határain belül és túl. A felhasználók használhatják az asztali klienst, mobilalkalmazásokat vagy webes felületet, és megjegyzéseket fűzhetnek, címkézhetnek, megoszthatnak és szerkeszthetnek fájlokat a Sharepoint-on, csakúgy, mint a Nextcloud bármely más adatait.\n\nA progam a Sharepoint 2013 és 2016 verziót támogatja. A Nextcloud a Sharepoint REST API-n keresztül éri el a Sharepointot, és NTLM hitelesítést használ. A Nextcloud megtartja a konfigurált felhasználói hitelesítő adatokhoz társított fájlhozzáférési engedélyeket. A verziószámosítást és a megosztást a Nextcloud kezeli.\n\nTudjon meg többet a külső tárhelyről és a Sharepointról a [https://nextcloud.com/storage/](https://nextcloud.com/storage/) oldalon.",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nRequires Nextcloud 10 or newer. Supports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "A Sharepoint háttérszolgáltatással az adminisztrátorok Sharepoint dokumentumtárakat adhatnak hozzá mappaként a Nextcloudhoz. Ez könnyű módot ad arra, hogy a felhasználók ugyanazon a helyen érjék el a Sharepoint adataikat, mint a többi fájljaikat, így lehetővé téve az együttműködést és megosztást a szervezet határain belül és kívül. A felhasználók használhatnak asztali klienst, mobilalkalmazást vagy a webes felületet, és megjegyzéseket, címkéket fűzhetnek hozzá, illetve közösen szerkeszthetnek fájlokat a Sharepointon, mint ahogy bármely más Nextcloud adattal tennék.\n\nNextcloud 10 vagy újabb szükséges. A Sharepoint 2013-at és 2016-ot támogatja. A Nextcloud a Sharepointot a REST API-ján keresztül használja, és NTLM hitelesítést használ. A Nextcloud tiszteletben tartja a hitelesítő adatokhoz beállított fájlelérési jogosultságokat. A verziókezelést és a megosztást a Nextcloud kezeli.\n\nTudjon meg többet a Külső tárolókról és a Sharepointról a [https://nextcloud.com/storage/](https://nextcloud.com/storage/) oldalon."
},
"nplurals=2; plural=(n != 1);");
