OC.L10N.register(
    "sharepoint",
    {
    "Enforce NTLM auth" : "Įgalinti NTLM autentifikavimą",
    "Acquiring a SAML token is attempted first by default." : "Pagal numatytuosius nustatymus pirmiausia bandoma gauti SAML prieigos raktą.",
    "SharePoint" : "„SharePoint“",
    "Host" : "Serveris",
    "Document Library" : "Dokumentų biblioteka",
    "SharePoint Backend" : "„SharePoint“ posistemė",
    "SharePoint Backend for External storages" : "„SharePoint“ posistemė ir išorinės saugyklos",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nSupports Sharepoint 2013, 2016 and 365. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "„SharePoint“ posistemė leidžia administratoriams pridėti „SharePoint“ dokumentų bibliotekas kaip aplankus „Nextcloud“ sistemoje. Tai suteikia vartotojams paprastą būdą pasiekti „SharePoint“ duomenis toje pačioje vietoje, kur jie randa kitus savo failus, taip palengvinant bendradarbiavimą ir dalijimąsi tiek organizacijos viduje, tiek už jos ribų. Vartotojai gali naudotis darbalaukio programa, mobiliosiomis programėlėmis arba žiniatinklio sąsaja ir komentuoti, žymėti, dalytis bei bendrai redaguoti failus „SharePoint“ sistemoje lygiai taip pat, kaip ir bet kuriuos kitus duomenis „Nextcloud“ sistemoje.\n\nPalaiko „Sharepoint 2013“, „2016“ ir „365“. „Nextcloud“ prieina prie „Sharepoint“ per „Sharepoint REST API“ ir naudoja NTLM autentifikavimą. „Nextcloud“ laikosi failų prieigos teisių, susijusių su jo sukonfigūruotais vartotojo prisijungimo duomenimis. Versijų valdymą ir dalijimąsi tvarko „Nextcloud“.\n\nSužinokite daugiau apie išorinę saugyklą ir „SharePoint“ adresu [https://nextcloud.com/storage/](https://nextcloud.com/storage/)"
},
"nplurals=4; plural=(n % 10 == 1 && (n % 100 > 19 || n % 100 < 11) ? 0 : (n % 10 >= 2 && n % 10 <=9) && (n % 100 > 19 || n % 100 < 11) ? 1 : n % 1 != 0 ? 2: 3);");
