OC.L10N.register(
    "sharepoint",
    {
    "Enforce NTLM auth" : "Wymuś uwierzytelnianie NTLM",
    "Acquiring a SAML token is attempted first by default." : "Domyślnie w pierwszej kolejności następuje próba uzyskania tokenu SAML.",
    "SharePoint" : "SharePoint",
    "Host" : "Host",
    "Document Library" : "Biblioteka Dokumenty",
    "SharePoint Backend" : "Backend SharePoint",
    "SharePoint Backend for External storages" : "Backend SharePoint dla magazynów zewnętrznych",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nSupports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Sharepoint Backend umożliwia administratorom dodawanie bibliotek dokumentów Sharepoint jako folderów w Nextcloud. Daje to użytkownikom łatwy sposób uzyskiwania dostępu do danych Sharepoint w tym samym miejscu, w którym znajdują swoje inne pliki, ułatwiając współpracę i udostępnianie w obrębie organizacji i poza jej granicami. Użytkownicy mogą korzystać z klienta stacjonarnego, aplikacji mobilnych lub interfejsu internetowego i komentować, oznaczać, udostępniać i wspólnie edytować pliki w Sharepoint, tak jak w przypadku innych danych w Nextcloud.\n\nObsługuje Sharepoint 2013 i 2016. Nextcloud uzyskuje dostęp do Sharepoint za pośrednictwem Sharepoint REST API i używa uwierzytelniania NTLM. Nextcloud respektuje uprawnienia dostępu do plików związane z jego skonfigurowanymi poświadczeniami użytkownika. Wersjonowanie i udostępnianie są obsługiwane przez Nextcloud.\n\nDowiedz się więcej o pamięci zewnętrznej i Sharepoint na [https://nextcloud.com/storage/](https://nextcloud.com/storage/)",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nRequires Nextcloud 10 or newer. Supports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Sharepoint Backend pozwala administratorom na dodawanie bibliotek dokumentów Sharepoint jako folderów w Nextcloud. To umożliwia użytkownikom łatwy dostęp do danych Sharepoint w tym samym miejscu gdzie znajdą inne pliki, umożliwiając współpracę i dzielenie się wewnątrz i poza granicami organizacji. Użytkownicy mogą stosować klienta dla komputerów stacjonarnych, aplikacje mobilne lub interfejs sieciowy i komentować, tagować, udostępniać i wspólnie edytować pliki na Sharepoint tak jak z dowolnymi innymi danymi na Nextcloud.\n\nWymaga wersji Nextcloud 10 lub nowszej. Wspiera Sharepoint 2013 i 2016. Nextcloud uzyskuje dostęp do Sharepoint przez Sharepoint REST API i wykorzystuje uwierzytelnianie NTLM. Nextcloud respektuje uprawnienia uprawnienia dostępu do plików skojarzone ze skonfigurowanymi dla nich poświadczeniami użytkowników. Wersjonowanie i udostępnianie są obsługiwane przez Nextcloud.\n\nDowiedz się więcej o Zewnętrznym przechowywaniu i Sharepoint na [https://nextcloud.com/storage/](https://nextcloud.com/storage/)"
},
"nplurals=4; plural=(n==1 ? 0 : (n%10>=2 && n%10<=4) && (n%100<12 || n%100>14) ? 1 : n!=1 && (n%10>=0 && n%10<=1) || (n%10>=5 && n%10<=9) || (n%100>=12 && n%100<=14) ? 2 : 3);");
