OC.L10N.register(
    "sharepoint",
    {
    "Enforce NTLM auth" : "Vsili overitev NTLM",
    "Acquiring a SAML token is attempted first by default." : "Pridobivanje žetona SAML je privzeto izvedeno prvo.",
    "SharePoint" : "Okolje SharePoint",
    "Host" : "Gostitelj",
    "Document Library" : "Knjižnica dokumentov",
    "SharePoint Backend" : "Ozadnji program SharePoint",
    "SharePoint Backend for External storages" : "Ozadnji program SharePoint za zunanje shrambe",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nRequires Nextcloud 10 or newer. Supports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Programsko okolje SharePoint omogoča skrbnikom, da dodajo knjižnice dokumentov Sharepoint kot mape v oblak Nextcloud. To omogoča uporabnikom enostaven način dostopa do podatkov Sharepoint znotraj enotnega okolja, kjer imajo tudi druge datoteke, olajša sodelovalno delo in skupno rabo znotraj ustanove ali med njimi. Uporabniki lahko uporabljajo namizni odjemalec, programe na mobilnih napravah ali spletni vmesnik in komentirajo, označujejo, izmenjujejo in skupaj urejajo datoteke na Sharepoint enako kot datoteke i podatke Nextcloud.\n\nOkolje zahteva različico Nextcloud 10 ali novejšo, podpira pa sta okolja Sharepoint 2013 in 2016. Nextcloud zagotovi dostop do datotek Sharepoint prek vmesnika Sharepoint REST API in uporablja overitveni protokol NTLM. Nextcloud upošteva dovoljenja za dostop do datotek, povezana z nastavljenimi uporabniškimi poverili. Različice in urejanje upravlja Nextcloud.\n\nVeč o zunanjem shranjevanju in o okolju SharePoint je objavljenih na spletni strani [https://nextcloud.com/storage/](https://nextcloud.com/storage/)",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nSupports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Ozadnji program Sharepoint omogoča skrbnikom dodajanje knjižnice dokumentov Sharepoint kot mape v oblak Nextcloud. To uporabnikom omogoča enostaven dostop do podatkov Sharepoint, kjer so tudi druge datoteke, s tem pa se olajša sodelovanje in poenostavi skupna uporaba datotek znotraj in zunaj ustanove. Uporabniki lahko pri tem uporabljajo namizni odjemalec, mobilne aplikacije ali spletni vmesnik ter komentirajo, označujejo, izmenjujejo, delijo in skupno urejajo datoteke v Sharepointu, tako kot druge vire v okolju Nextcloud.\n\nPodprti sta različici Sharepoint 2013 in 2016. Povezovanje poteka prek vmesnika API Sharepoint REST in uporablja overjanje NTLM. Upoštevana so vsa sistemska dovoljenja za dostop do datotek, ki so povezana z overjenimi uporabniškimi poverilnicami. Sledenje različic in skupna raba se izvajata prek protokolov Nextcloud.\n\nVeč o zunanjem pomnilniku in zbirniku SharePoint je zavedeno na spletni strani [https://nextcloud.com/storage/](https://nextcloud.com/storage/)"
},
"nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3);");
