OC.L10N.register(
    "sharepoint",
    {
    "SharePoint" : "SharePoint",
    "Host" : "Домаћин",
    "Document Library" : "Библиотека докумената",
    "SharePoint Backend" : "SharePoint позадински мотор",
    "SharePoint Backend for External storages" : "SharePoint позадински мотор за спољашња складишта",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nRequires Nextcloud 10 or newer. Supports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Sharepoint позадински мотор дозвољава администраторима да додају Sharepoint библиотеке докумената као фасцикле у Некстклауд. Ово омогућава лак начин да корисници приступају Sharepoint подацима на месту на којем већ налазе и остале фајлове, омогућујући заједнички рад и дељење и ван граница организације. Корисници могу да користе десктоп клијента, мобилне апликације или веб интерфејс и да коментаришу, додају ознаке, деле и заједнички уређују фајлове на Sharepoint-у као и било које друге податке у оквиру Некстклауда.\n\nЗахтева Некстклауд верзију 10 или новију. Подржани су Sharepoint 2013 и 2016. Некстклауд приступа Sharepoint-у преко Sharepoint REST API-ја и користи NTLM идентификацију. Некстклауд поштује дозволе приступању фајлу повезане са акредитивима подешеног корисника. Верзионисање и дељење су преко Некстклауда.\n\nСазнајте више о спољашњем складишту и Sharepoint-у на [https://nextcloud.com/storage/](https://nextcloud.com/storage/)"
},
"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);");
