OC.L10N.register(
    "sharepoint",
    {
    "Enforce NTLM auth" : "Застосувати автентифікацію NTLM",
    "Acquiring a SAML token is attempted first by default." : "За замовчуванням спочатку намагається отримати маркер SAML.",
    "SharePoint" : "SharePoint",
    "Host" : "Хост",
    "Document Library" : "Бібліотека документів",
    "SharePoint Backend" : "Двигун SharePoint",
    "SharePoint Backend for External storages" : "Двигун SharePoint для Зовнішніх сховищ",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nSupports Sharepoint 2013, 2016 and 365. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Сервер Sharepoint дозволяє адміністраторам додавати бібліотеки документів Sharepoint як папки в Nextcloud. Це пропонує користувачам простий спосіб отримати доступ до даних Sharepoint у тому самому місці, де вони знаходять свої інші файли, полегшуючи співпрацю та обмін всередині та за межами організації. Користувачі можуть використовувати настільний клієнт, мобільні програми або веб-інтерфейс і коментувати, позначати, ділитися та спільно редагувати файли на Sharepoint так само, як і з будь-якими іншими даними на Nextcloud. Підтримує Sharepoint 2013, 2016 і 365. Nextcloud отримує доступ до Sharepoint через Sharepoint REST API і використовує автентифікацію NTLM. Nextcloud поважає дозволи на доступ до файлів, пов’язані з налаштованими обліковими даними користувача. Контроль версій і спільне використання обробляються Nextcloud. Дізнайтесь більше про зовнішнє сховище та Sharepoint на [https://nextcloud.com/storage/](https://nextcloud.com/storage/)",
    "The Sharepoint Backend allows administrators to add Sharepoint document libraries as folders in Nextcloud. This offers an easy way for users to access Sharepoint data in the same place where they find their other files, facilitating collaboration and sharing within and across the borders of the organization. Users can use the desktop client, mobile apps or web interface and comment, tag, share and collaboratively edit files on Sharepoint just like with any other data on Nextcloud.\n\nSupports Sharepoint 2013 and 2016. Nextcloud accesses Sharepoint through the Sharepoint REST API and uses NTLM authentication. Nextcloud respects file access permissions associated with its configured user credentials. Versioning and sharing are handled by Nextcloud.\n\nLearn more about External Storage and Sharepoint on [https://nextcloud.com/storage/](https://nextcloud.com/storage/)" : "Сервер Sharepoint дозволяє адміністраторам додавати бібліотеки документів Sharepoint як папки в Nextcloud. Це пропонує користувачам простий спосіб отримати доступ до даних Sharepoint у тому самому місці, де вони знаходять свої інші файли, полегшуючи співпрацю та обмін всередині та за межами організації. Користувачі можуть використовувати настільний клієнт, мобільні програми або веб-інтерфейс і коментувати, позначати, ділитися та спільно редагувати файли на Sharepoint так само, як і з будь-якими іншими даними на Nextcloud. Підтримує Sharepoint 2013 і 2016. Nextcloud отримує доступ до Sharepoint через Sharepoint REST API і використовує автентифікацію NTLM. Nextcloud поважає дозволи на доступ до файлів, пов’язані з налаштованими обліковими даними користувача. Контроль версій і спільне використання обробляються Nextcloud. Дізнайтесь більше про зовнішнє сховище та Sharepoint на [https://nextcloud.com/storage/](https://nextcloud.com/storage/)"
},
"nplurals=4; plural=(n % 1 == 0 && n % 10 == 1 && n % 100 != 11 ? 0 : n % 1 == 0 && n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14) ? 1 : n % 1 == 0 && (n % 10 ==0 || (n % 10 >=5 && n % 10 <=9) || (n % 100 >=11 && n % 100 <=14 )) ? 2: 3);");
